services:
  nextcloud-talk-recording:
    image: ghcr.io/scott_howson/nextcloud-talk-recording:latest
    init: true
    shm_size: '2gb'
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - nextcloud-talk-recording
    # Optional: Mount custom config
    # volumes:
    #   - ./custom-server.conf:/etc/nextcloud-talk-recording/server.conf:ro
    # Optional: Environment variables
    # environment:
    #   - NEXTCLOUD_URL=https://your-nextcloud.example.com
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import socket; s=socket.socket(); s.settimeout(1); s.connect((\"127.0.0.1\", 8000)); s.close()' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  nextcloud-talk-recording:

# Optional: Add logging configuration
# logging:
#   driver: "json-file"
#   options:
#     max-size: "100m"
#     max-file: "3"