# docker-compose.yml - Scott Howson's Nextcloud Talk Recording Setup
version: "3.9"

services:
  nextcloud-talk-recording:
    image: ghcr.io/scotthowson/nextcloud-talk-recording:latest
    init: true
    shm_size: '2gb'
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NC_DOMAIN=cloud.scotthowson.io
      - RECORDING_SECRET=abc123...  # Generate with: openssl rand -hex 32
      - SIGNALING_URL=https://signaling.scotthowson.io
      - SIGNALING_INTERNAL_SECRET=def456...  # From your signaling server config
    networks:
      - nextcloud-talk-recording
    volumes:
      - ./recordings:/tmp/recordings
    networks:
      - nextcloud-talk-recording
  
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import socket; s=socket.socket(); s.settimeout(1); s.connect((\"127.0.0.1\", 8000)); s.close()' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  nextcloud-talk-recording:

volumes:
  recordings: